version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  nginx: 
    build: ./nginx
    expose:
      - "80"
    volumes:
      - .:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=localhost
  
  nextjs: 
    build: ./
  
